# This is a basic workflow to help you get started with Actions

name: Readme

# Controls when the workflow will run
on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: beatrizsmerino/waka-readme-stats@master  # instead of anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "False"
          SHOW_DAYS_OF_WEEK: "False"
          LOCALE: "False"
          IGNORED_REPOS: "False"
          SHOW_UPDATED_DATE: "False"
          UPDATED_DATE_FORMAT: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          COMMIT_MESSAGE: "False"
          SHOW_SHORT_INFO: "False"
